# Generated by Django 3.1.5 on 2021-05-03 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210503_0631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='contact_no',
        ),
    ]
