# Generated by Django 3.1.5 on 2021-05-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_customers_contact_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='contact_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
