# Generated by Django 3.1.5 on 2021-05-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_customers_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='contact_no',
            field=models.IntegerField(max_length=200),
        ),
    ]
