# Generated by Django 3.1.5 on 2021-05-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210503_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
