# Generated by Django 3.1.5 on 2021-05-03 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_transactions_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='paid',
            new_name='reciever',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='recieved',
            new_name='sender',
        ),
    ]
